name: Build and Push & Deploy Docker Image of backend service

on:
  push:
    branches:
      - main
    paths:
      - apps/backend/package.json
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v3

      - name: Install Bun latest
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Extract version from package.json
        run: |
          VERSION=$(bun -p "require('./apps/backend/package.json').version")
          echo "version=${VERSION}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Create .env file from GitHub secret
        run: |
          echo "${{ secrets.BACKEND_ENVS }}" > ./apps/backend/.env

      - name: Install dependencies
        working-directory: ./apps/backend
        run: bun install

      - name: Run migrations
        working-directory: ./apps/backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: bun run db:migrate

      - name: Set IMAGE_NAME and IMAGE_TAG
        run: |
          echo "IMAGE_NAME=${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO_NAME}}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ env.version }}" >> $GITHUB_ENV

      - name: Docker Compose Build & Push
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{env.IMAGE_TAG}}
        run: |
          # REMOTE_IMAGE_NAME=${IMAGE_NAME}:${IMAGE_TAG} docker compose -f docker-compose.yml build backend
          REMOTE_IMAGE_NAME=${IMAGE_NAME}:latest docker compose -f docker-compose.yml build backend
          # REMOTE_IMAGE_NAME=${IMAGE_NAME}:${IMAGE_TAG} docker compose -f docker-compose.yml push backend
          REMOTE_IMAGE_NAME=${IMAGE_NAME}:latest docker compose -f docker-compose.yml push backend

      - name: Trigger Render deploy
        env:
          DEPLOY_URL: ${{secrets.RENDER_DEPLOY_HOOK_URL}}
        run: |
          curl "${DEPLOY_URL}"

      - name: Notify if push fails
        if: failure()
        run: echo "Docker Compose push failed" | tee /dev/stderr
